### ISSUE TITLE
[Invoice Page] Refactor code

### ISSUE THREAD

**Issue by dylan751** [dylan751/sushi#110]
## Why
- Makes code more clean, consistent, ...

## Tasks
- [ ] Remove unused code/section
  - [ ] Remove `invoiceTypes.ts`
  - [ ] Remove `AddNewCustomer.tsx`
  - [ ] Remove `AddPaymentDrawer.tsx`
  - [ ] Remove `SendInvoiceDrawer.tsx`
  - [ ] Remove unused sections (buttons, functions, ...): Inside Preview, Print, ... pages
