### ISSUE TITLE
[Invoice Page] Support multiple items for 1 Invoice

### ISSUE THREAD

**Issue by dylan751** [dylan751/sushi#115]
## Why
- 1 invoice should includes multiple items

## Tasks
- [x] Regen API
- [x] Add Invoice: Implement logic for `<Repeater />` component
- [x] Update Invoice: Implement logic for `<Repeater />` component
  - [x] UI bug: Edit -> Preview -> Edit: Lost `data in UI`, but the `formData` is still right (only UI bug?)
- [x] Get 1/all Invoice: Change due to the format change from BE
- [x] Preview Invoice: Change due to the format change from BE
- [x] Print Invoice: : Change due to the format change from BE
- [x] Delete Invoice: Maybe nothing needs to be changed

## Bugs
- [x] Change any -> DTOs
- [x] After Add/Update Invoice -> data still get cached, so UI is empty but users still can submit -> bad UX
  - [x] Reason: setFormData seems not right. After `setFormData`, the formData auto insert new record with the value of the first record
  - [x] Update: check `initialFormData`, it contains the value of first item, instead of empty object

## API
https://github.com/dylan751/ramen/issues/58
