### ISSUE TITLE
[Project Management] Refactor project page code

### ISSUE THREAD

**Issue by dylan751** [dylan751/sushi#143]
## Why
- Makes code cleaner
- Fix some logic for Project management in FE

## Tasks
- [ ] Khi tạo Budget: mặc định là Expense (ko cho phép tạo Budget vs type Income) - Chỉ khoá ở UI, chứ API thì vẫn cho (để sau này mở rộng nếu cần thiết)
- [ ] Khi chọn expense hoặc income, render đúng Category thuộc loại đó
- [ ] TODO: Render dynamic total budget spent in `project list page`
- [ ] Thêm filter cho project, budget, category, ...
