### ISSUE TITLE
[New Organization Page] Update create organization page

### ISSUE THREAD

**Issue by dylan751** [dylan751/sushi#153]
## Why
- Update `create organization page`

## Tasks
- [ ] Validate orgUniqueName: regex
- [ ] Chỉnh UI cho giống Admina
- [ ] Add `Create new org` button on `/organization` page
- [ ] Thêm đăng ký địa chỉ, sđt org
- [ ] Organization settings page
